openapi: 3.0.0
info:
  title: User Module API
  description: API for authentication and user management using Azure AD SSO
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
    description: Production Server
  - url: 'http://localhost:3000'
    description: Local Development
paths:
  /users/profile:
    get:
      summary: Get authenticated user profile
      description: Returns the logged-in user's details extracted from Azure AD JWT.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
        '401':
          description: Unauthorized
  /users/is-admin:
    get:
      summary: Check if user is an admin
      description: Determines if the logged-in user has Admin role.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  isAdmin:
                    type: boolean
        '401':
          description: Unauthorized
  /users/validate-token:
    post:
      summary: Validate Azure AD JWT token
      description: Verifies if the provided token is valid.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        '401':
          description: Invalid token
  /users/logout:
    post:
      summary: Logs out the user
      description: Ends the user's session (frontend session cleanup).
      responses:
        '200':
          description: Logout successful
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
